version: '3'

services:
    jenkins:
        image: jenkins/jenkins:jdk11
        container_name: jenkins_compose
    ports:
        - "50000:50000"
        - "8880:8080"
    volumes:
        - ../volumes/jenkins:/var/jenkins_home
    networks: 
        - docker_network
    ubuntuslave:
    